services:
  proxy-gateway:
    build: ./proxy-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - profile-service
      - data-service
      - report-service
#      - log-service
    networks:
      - app-net

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - database-service
      - redis
    environment:
      - DB_HOST=database-service
      - REDIS_HOST=redis
    networks:
      - app-net

  profile-service:
    build: ./profile-service
    depends_on:
      - database-service
      - redis
    environment:
      - DB_HOST=database-service
      - REDIS_HOST=redis
    networks:
      - app-net

  data-service:
    build: ./data-service
    depends_on:
      - database-service
      - redis
      - rabbitmq
    environment:
      - DB_HOST=database-service
      - REDIS_HOST=redis
      - RABBIT_HOST=rabbitmq
    networks:
      - app-net

  report-service:
    build: ./report-service
    depends_on:
      - database-service
      - clickhouse
      - rabbitmq
      - redis
    environment:
      - DB_HOST=database-service
      - CLICKHOUSE_HOST=clickhouse
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=redis
    networks:
      - app-net

#  log-service:
#    build: ./log-service
#    depends_on:
#      - database-service
#      - rabbitmq
#    environment:
#      - DB_HOST=database-service
#      - RABBIT_HOST=rabbitmq
#    networks:
#      - app-net

  database-service:
    build: ./database-service
    ports:
      - "8083:8080"
    depends_on:
      - postgres
      - clickhouse
    environment:
      - POSTGRES_HOST=postgres
      - CLICKHOUSE_HOST=clickhouse
    networks:
      - app-net

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-net

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-net

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    restart: always
    ports:
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - app-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # UI
      - "5672:5672"    # AMQP
    networks:
      - app-net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent data for RabbitMQ
    restart: always

volumes:
  pg_data:
  clickhouse_data:
  rabbitmq_data:
    driver: local

networks:
  app-net: