### Register User
POST http://localhost:8081/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword",
  "age": 30,
  "weight": 72.5,
  "height": 178.0,
  "gender": "male",
  "goal": "похудеть"
}

### Login User
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

### Verify Token (поставить сюда токен из логина)
GET http://localhost:8081/auth/verify
Authorization: Bearer 94932960-af54-4993-9be9-06b65884bb25
